### ISSUE TITLE
Bug: NullPointerException in GraphDraw.drawNodeSetManagerGrid

### ISSUE THREAD

**Issue by erictapen** [erictapen/weird-tree-plot#19]
```
Exception in thread "Animation Thread" java.lang.NullPointerException
    at draw.GraphDraw.drawNodeSetManagerGrid(GraphDraw.java:195)
    at draw.GraphDraw.draw(GraphDraw.java:95)
    at processing.core.PApplet.handleDraw(PApplet.java:2386)
    at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:240)
    at processing.core.PApplet.run(PApplet.java:2256)
    at java.lang.Thread.run(Thread.java:745)
```

happened at 22628 plottedNodes.

**Comment by erictapen** [comment]
another occurence at the exact same line of code after 17381 plottedNodes, but this time it is a ClassCastException: cannot be cast to java.lang.Integer

**Comment by erictapen** [comment]
another:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fedf8375871, pid=5268, tid=140660000016128
#
# JRE version: OpenJDK Runtime Environment (7.0_85-b01) (build 1.7.0_85-b01)
# Java VM: OpenJDK 64-Bit Server VM (24.85-b03 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 2.6.1
# Distribution: Ubuntu 14.04 LTS, package 7u85-2.6.1-5ubuntu0.14.04.1
# Problematic frame:
# V  [libjvm.so+0x7b8871]  objArrayKlass::oop_follow_contents(ParCompactionManager*, oopDesc*)+0x2e1
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/justin/git/wikipedia-map/hs_err_pid5268.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
#
```

**Comment by erictapen** [comment]
[hs_err_pid5268.log.txt](https://github.com/erictapen/weird-tree-plot/files/24956/hs_err_pid5268.log.txt)

**Comment by erictapen** [comment]
`java.lang.String cannot be cast to java.lang.Integer`

**Comment by erictapen** [comment]
```
Exception in thread "Animation Thread" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to java.util.Vector
    at draw.GraphDraw.drawNodeSetManagerGrid(GraphDraw.java:192)
    at draw.GraphDraw.draw(GraphDraw.java:95)
    at processing.core.PApplet.handleDraw(PApplet.java:2386)
    at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:240)
    at processing.core.PApplet.run(PApplet.java:2256)
    at java.lang.Thread.run(Thread.java:745)
```
